version: '3.8'

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000" # Blob service
      - "10001:10001" # Queue service
      - "10002:10002" # Table service
    volumes:
      - azurite_data:/data

  azure-cli:
    image: mcr.microsoft.com/azure-cli
    container_name: azure-cli
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: sleep infinity

volumes:
  azurite_data: 