name: API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VAULT_ADDR: "http://localhost:8200"
      VAULT_TOKEN: "dev-token"
      AZURE_STORAGE_ACCOUNT: "devstoreaccount1"
      AZURE_STORAGE_KEY: "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="
      BLOB_STORAGE_URL: "http://127.0.0.1:10000/devstoreaccount1"
      CONTAINER_NAME: "files"
      USE_AZURITE: "true"

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Setup services and run tests
      run: |
        docker-compose up -d
        sleep 10  # Give services time to start
        ./scripts/test-api.sh 